project:
  type: website
  output-dir: _site
  render: 
    - index.qmd
    - Section 1.qmd
    - Section 2.qmd
    - Section 3.qmd
    - Section 4.qmd
    - Section 5.qmd
    - about.qmd

website:
  title: "Responsible Research Assessment and Use of Research Metrics Quick Guide"
  repo-url: "https://github.com/UniSotonLibrary/responsible-metrics/"
  repo-branch: main
  repo-actions:
  - edit
  - issue
  google-analytics: 
    tracking-id: "G-KBY6B9VX9V"
  navbar:
    logo: "images/UoE logo 150px.png"
    left:
      - href: index.qmd
        text: Home
      - Section 1.qmd
      - Section 2.qmd
      - Section 3.qmd
      - Section 4.qmd
      - Section 5.qmd
      - about.qmd
  
  sidebar: 
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: "Home"
      - href: Section 1.qmd
        text: "Section 1"
      - href: Section 2.qmd
        text: "Section 2"
      - href: Section 3.qmd
        text: "Section 3"
      - href: Section 4.qmd
        text: "Section 4"
      - href: Section 5.qmd
        text: "Section 5"
      - href: about.qmd
        text: "About"
        
  back-to-top-navigation: true
  page-navigation: true  
  page-footer: "Adapted by Alex Peden, University of Edinburgh from a module developed by Kate Lapage, Clare Hemmings and Lorrayne Smith @ University of Southampton Library and shared under a CC BY licence"
      
format:
  html:
    link-external-newwindow: true
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

